// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/logstash.proto

package org.apache.mesos.logstash.common;

public final class LogstashProtos {
  private LogstashProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogstashConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.mesos.logstash.common.LogstashConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string frameworkName = 1;</code>
     */
    boolean hasFrameworkName();
    /**
     * <code>required string frameworkName = 1;</code>
     */
    java.lang.String getFrameworkName();
    /**
     * <code>required string frameworkName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFrameworkNameBytes();

    /**
     * <code>required string config = 2;</code>
     */
    boolean hasConfig();
    /**
     * <code>required string config = 2;</code>
     */
    java.lang.String getConfig();
    /**
     * <code>required string config = 2;</code>
     */
    com.google.protobuf.ByteString
        getConfigBytes();
  }
  /**
   * Protobuf type {@code org.apache.mesos.logstash.common.LogstashConfig}
   */
  public static final class LogstashConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.apache.mesos.logstash.common.LogstashConfig)
      LogstashConfigOrBuilder {
    // Use LogstashConfig.newBuilder() to construct.
    private LogstashConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogstashConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogstashConfig defaultInstance;
    public static LogstashConfig getDefaultInstance() {
      return defaultInstance;
    }

    public LogstashConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogstashConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              frameworkName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              config_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_LogstashConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_LogstashConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.class, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<LogstashConfig> PARSER =
        new com.google.protobuf.AbstractParser<LogstashConfig>() {
      public LogstashConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogstashConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogstashConfig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FRAMEWORKNAME_FIELD_NUMBER = 1;
    private java.lang.Object frameworkName_;
    /**
     * <code>required string frameworkName = 1;</code>
     */
    public boolean hasFrameworkName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string frameworkName = 1;</code>
     */
    public java.lang.String getFrameworkName() {
      java.lang.Object ref = frameworkName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          frameworkName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string frameworkName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFrameworkNameBytes() {
      java.lang.Object ref = frameworkName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        frameworkName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONFIG_FIELD_NUMBER = 2;
    private java.lang.Object config_;
    /**
     * <code>required string config = 2;</code>
     */
    public boolean hasConfig() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string config = 2;</code>
     */
    public java.lang.String getConfig() {
      java.lang.Object ref = config_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          config_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string config = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConfigBytes() {
      java.lang.Object ref = config_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        config_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      frameworkName_ = "";
      config_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFrameworkName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConfig()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getFrameworkNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getConfigBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getFrameworkNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getConfigBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.mesos.logstash.common.LogstashConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.mesos.logstash.common.LogstashConfig)
        org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_LogstashConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_LogstashConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.class, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder.class);
      }

      // Construct using org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        frameworkName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        config_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_LogstashConfig_descriptor;
      }

      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig getDefaultInstanceForType() {
        return org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.getDefaultInstance();
      }

      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig build() {
        org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig buildPartial() {
        org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig result = new org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.frameworkName_ = frameworkName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.config_ = config_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig) {
          return mergeFrom((org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig other) {
        if (other == org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.getDefaultInstance()) return this;
        if (other.hasFrameworkName()) {
          bitField0_ |= 0x00000001;
          frameworkName_ = other.frameworkName_;
          onChanged();
        }
        if (other.hasConfig()) {
          bitField0_ |= 0x00000002;
          config_ = other.config_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFrameworkName()) {
          
          return false;
        }
        if (!hasConfig()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object frameworkName_ = "";
      /**
       * <code>required string frameworkName = 1;</code>
       */
      public boolean hasFrameworkName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string frameworkName = 1;</code>
       */
      public java.lang.String getFrameworkName() {
        java.lang.Object ref = frameworkName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            frameworkName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string frameworkName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFrameworkNameBytes() {
        java.lang.Object ref = frameworkName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          frameworkName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string frameworkName = 1;</code>
       */
      public Builder setFrameworkName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        frameworkName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string frameworkName = 1;</code>
       */
      public Builder clearFrameworkName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frameworkName_ = getDefaultInstance().getFrameworkName();
        onChanged();
        return this;
      }
      /**
       * <code>required string frameworkName = 1;</code>
       */
      public Builder setFrameworkNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        frameworkName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object config_ = "";
      /**
       * <code>required string config = 2;</code>
       */
      public boolean hasConfig() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string config = 2;</code>
       */
      public java.lang.String getConfig() {
        java.lang.Object ref = config_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            config_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string config = 2;</code>
       */
      public com.google.protobuf.ByteString
          getConfigBytes() {
        java.lang.Object ref = config_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          config_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string config = 2;</code>
       */
      public Builder setConfig(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        config_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string config = 2;</code>
       */
      public Builder clearConfig() {
        bitField0_ = (bitField0_ & ~0x00000002);
        config_ = getDefaultInstance().getConfig();
        onChanged();
        return this;
      }
      /**
       * <code>required string config = 2;</code>
       */
      public Builder setConfigBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        config_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.apache.mesos.logstash.common.LogstashConfig)
    }

    static {
      defaultInstance = new LogstashConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.apache.mesos.logstash.common.LogstashConfig)
  }

  public interface SchedulerMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.mesos.logstash.common.SchedulerMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> 
        getDockerConfigList();
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig getDockerConfig(int index);
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    int getDockerConfigCount();
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    java.util.List<? extends org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> 
        getDockerConfigOrBuilderList();
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder getDockerConfigOrBuilder(
        int index);

    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> 
        getHostConfigList();
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig getHostConfig(int index);
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    int getHostConfigCount();
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    java.util.List<? extends org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> 
        getHostConfigOrBuilderList();
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder getHostConfigOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.apache.mesos.logstash.common.SchedulerMessage}
   */
  public static final class SchedulerMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.apache.mesos.logstash.common.SchedulerMessage)
      SchedulerMessageOrBuilder {
    // Use SchedulerMessage.newBuilder() to construct.
    private SchedulerMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SchedulerMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SchedulerMessage defaultInstance;
    public static SchedulerMessage getDefaultInstance() {
      return defaultInstance;
    }

    public SchedulerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SchedulerMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dockerConfig_ = new java.util.ArrayList<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig>();
                mutable_bitField0_ |= 0x00000001;
              }
              dockerConfig_.add(input.readMessage(org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                hostConfig_ = new java.util.ArrayList<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig>();
                mutable_bitField0_ |= 0x00000002;
              }
              hostConfig_.add(input.readMessage(org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dockerConfig_ = java.util.Collections.unmodifiableList(dockerConfig_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          hostConfig_ = java.util.Collections.unmodifiableList(hostConfig_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_SchedulerMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_SchedulerMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage.class, org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<SchedulerMessage> PARSER =
        new com.google.protobuf.AbstractParser<SchedulerMessage>() {
      public SchedulerMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SchedulerMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SchedulerMessage> getParserForType() {
      return PARSER;
    }

    public static final int DOCKERCONFIG_FIELD_NUMBER = 1;
    private java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> dockerConfig_;
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    public java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> getDockerConfigList() {
      return dockerConfig_;
    }
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    public java.util.List<? extends org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> 
        getDockerConfigOrBuilderList() {
      return dockerConfig_;
    }
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    public int getDockerConfigCount() {
      return dockerConfig_.size();
    }
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig getDockerConfig(int index) {
      return dockerConfig_.get(index);
    }
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
     */
    public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder getDockerConfigOrBuilder(
        int index) {
      return dockerConfig_.get(index);
    }

    public static final int HOSTCONFIG_FIELD_NUMBER = 2;
    private java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> hostConfig_;
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    public java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> getHostConfigList() {
      return hostConfig_;
    }
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    public java.util.List<? extends org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> 
        getHostConfigOrBuilderList() {
      return hostConfig_;
    }
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    public int getHostConfigCount() {
      return hostConfig_.size();
    }
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig getHostConfig(int index) {
      return hostConfig_.get(index);
    }
    /**
     * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
     */
    public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder getHostConfigOrBuilder(
        int index) {
      return hostConfig_.get(index);
    }

    private void initFields() {
      dockerConfig_ = java.util.Collections.emptyList();
      hostConfig_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDockerConfigCount(); i++) {
        if (!getDockerConfig(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getHostConfigCount(); i++) {
        if (!getHostConfig(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dockerConfig_.size(); i++) {
        output.writeMessage(1, dockerConfig_.get(i));
      }
      for (int i = 0; i < hostConfig_.size(); i++) {
        output.writeMessage(2, hostConfig_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dockerConfig_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dockerConfig_.get(i));
      }
      for (int i = 0; i < hostConfig_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, hostConfig_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.mesos.logstash.common.SchedulerMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.mesos.logstash.common.SchedulerMessage)
        org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_SchedulerMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_SchedulerMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage.class, org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage.Builder.class);
      }

      // Construct using org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDockerConfigFieldBuilder();
          getHostConfigFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dockerConfigBuilder_ == null) {
          dockerConfig_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dockerConfigBuilder_.clear();
        }
        if (hostConfigBuilder_ == null) {
          hostConfig_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          hostConfigBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_SchedulerMessage_descriptor;
      }

      public org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage getDefaultInstanceForType() {
        return org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage.getDefaultInstance();
      }

      public org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage build() {
        org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage buildPartial() {
        org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage result = new org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage(this);
        int from_bitField0_ = bitField0_;
        if (dockerConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dockerConfig_ = java.util.Collections.unmodifiableList(dockerConfig_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dockerConfig_ = dockerConfig_;
        } else {
          result.dockerConfig_ = dockerConfigBuilder_.build();
        }
        if (hostConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            hostConfig_ = java.util.Collections.unmodifiableList(hostConfig_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.hostConfig_ = hostConfig_;
        } else {
          result.hostConfig_ = hostConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage) {
          return mergeFrom((org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage other) {
        if (other == org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage.getDefaultInstance()) return this;
        if (dockerConfigBuilder_ == null) {
          if (!other.dockerConfig_.isEmpty()) {
            if (dockerConfig_.isEmpty()) {
              dockerConfig_ = other.dockerConfig_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDockerConfigIsMutable();
              dockerConfig_.addAll(other.dockerConfig_);
            }
            onChanged();
          }
        } else {
          if (!other.dockerConfig_.isEmpty()) {
            if (dockerConfigBuilder_.isEmpty()) {
              dockerConfigBuilder_.dispose();
              dockerConfigBuilder_ = null;
              dockerConfig_ = other.dockerConfig_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dockerConfigBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDockerConfigFieldBuilder() : null;
            } else {
              dockerConfigBuilder_.addAllMessages(other.dockerConfig_);
            }
          }
        }
        if (hostConfigBuilder_ == null) {
          if (!other.hostConfig_.isEmpty()) {
            if (hostConfig_.isEmpty()) {
              hostConfig_ = other.hostConfig_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureHostConfigIsMutable();
              hostConfig_.addAll(other.hostConfig_);
            }
            onChanged();
          }
        } else {
          if (!other.hostConfig_.isEmpty()) {
            if (hostConfigBuilder_.isEmpty()) {
              hostConfigBuilder_.dispose();
              hostConfigBuilder_ = null;
              hostConfig_ = other.hostConfig_;
              bitField0_ = (bitField0_ & ~0x00000002);
              hostConfigBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHostConfigFieldBuilder() : null;
            } else {
              hostConfigBuilder_.addAllMessages(other.hostConfig_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDockerConfigCount(); i++) {
          if (!getDockerConfig(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getHostConfigCount(); i++) {
          if (!getHostConfig(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.mesos.logstash.common.LogstashProtos.SchedulerMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> dockerConfig_ =
        java.util.Collections.emptyList();
      private void ensureDockerConfigIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dockerConfig_ = new java.util.ArrayList<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig>(dockerConfig_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> dockerConfigBuilder_;

      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> getDockerConfigList() {
        if (dockerConfigBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dockerConfig_);
        } else {
          return dockerConfigBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public int getDockerConfigCount() {
        if (dockerConfigBuilder_ == null) {
          return dockerConfig_.size();
        } else {
          return dockerConfigBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig getDockerConfig(int index) {
        if (dockerConfigBuilder_ == null) {
          return dockerConfig_.get(index);
        } else {
          return dockerConfigBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder setDockerConfig(
          int index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig value) {
        if (dockerConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDockerConfigIsMutable();
          dockerConfig_.set(index, value);
          onChanged();
        } else {
          dockerConfigBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder setDockerConfig(
          int index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder builderForValue) {
        if (dockerConfigBuilder_ == null) {
          ensureDockerConfigIsMutable();
          dockerConfig_.set(index, builderForValue.build());
          onChanged();
        } else {
          dockerConfigBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder addDockerConfig(org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig value) {
        if (dockerConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDockerConfigIsMutable();
          dockerConfig_.add(value);
          onChanged();
        } else {
          dockerConfigBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder addDockerConfig(
          int index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig value) {
        if (dockerConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDockerConfigIsMutable();
          dockerConfig_.add(index, value);
          onChanged();
        } else {
          dockerConfigBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder addDockerConfig(
          org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder builderForValue) {
        if (dockerConfigBuilder_ == null) {
          ensureDockerConfigIsMutable();
          dockerConfig_.add(builderForValue.build());
          onChanged();
        } else {
          dockerConfigBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder addDockerConfig(
          int index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder builderForValue) {
        if (dockerConfigBuilder_ == null) {
          ensureDockerConfigIsMutable();
          dockerConfig_.add(index, builderForValue.build());
          onChanged();
        } else {
          dockerConfigBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder addAllDockerConfig(
          java.lang.Iterable<? extends org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> values) {
        if (dockerConfigBuilder_ == null) {
          ensureDockerConfigIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dockerConfig_);
          onChanged();
        } else {
          dockerConfigBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder clearDockerConfig() {
        if (dockerConfigBuilder_ == null) {
          dockerConfig_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dockerConfigBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public Builder removeDockerConfig(int index) {
        if (dockerConfigBuilder_ == null) {
          ensureDockerConfigIsMutable();
          dockerConfig_.remove(index);
          onChanged();
        } else {
          dockerConfigBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder getDockerConfigBuilder(
          int index) {
        return getDockerConfigFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder getDockerConfigOrBuilder(
          int index) {
        if (dockerConfigBuilder_ == null) {
          return dockerConfig_.get(index);  } else {
          return dockerConfigBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public java.util.List<? extends org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> 
           getDockerConfigOrBuilderList() {
        if (dockerConfigBuilder_ != null) {
          return dockerConfigBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dockerConfig_);
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder addDockerConfigBuilder() {
        return getDockerConfigFieldBuilder().addBuilder(
            org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder addDockerConfigBuilder(
          int index) {
        return getDockerConfigFieldBuilder().addBuilder(
            index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig dockerConfig = 1;</code>
       */
      public java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder> 
           getDockerConfigBuilderList() {
        return getDockerConfigFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> 
          getDockerConfigFieldBuilder() {
        if (dockerConfigBuilder_ == null) {
          dockerConfigBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder>(
                  dockerConfig_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dockerConfig_ = null;
        }
        return dockerConfigBuilder_;
      }

      private java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> hostConfig_ =
        java.util.Collections.emptyList();
      private void ensureHostConfigIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          hostConfig_ = new java.util.ArrayList<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig>(hostConfig_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> hostConfigBuilder_;

      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> getHostConfigList() {
        if (hostConfigBuilder_ == null) {
          return java.util.Collections.unmodifiableList(hostConfig_);
        } else {
          return hostConfigBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public int getHostConfigCount() {
        if (hostConfigBuilder_ == null) {
          return hostConfig_.size();
        } else {
          return hostConfigBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig getHostConfig(int index) {
        if (hostConfigBuilder_ == null) {
          return hostConfig_.get(index);
        } else {
          return hostConfigBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder setHostConfig(
          int index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig value) {
        if (hostConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHostConfigIsMutable();
          hostConfig_.set(index, value);
          onChanged();
        } else {
          hostConfigBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder setHostConfig(
          int index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder builderForValue) {
        if (hostConfigBuilder_ == null) {
          ensureHostConfigIsMutable();
          hostConfig_.set(index, builderForValue.build());
          onChanged();
        } else {
          hostConfigBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder addHostConfig(org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig value) {
        if (hostConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHostConfigIsMutable();
          hostConfig_.add(value);
          onChanged();
        } else {
          hostConfigBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder addHostConfig(
          int index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig value) {
        if (hostConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHostConfigIsMutable();
          hostConfig_.add(index, value);
          onChanged();
        } else {
          hostConfigBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder addHostConfig(
          org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder builderForValue) {
        if (hostConfigBuilder_ == null) {
          ensureHostConfigIsMutable();
          hostConfig_.add(builderForValue.build());
          onChanged();
        } else {
          hostConfigBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder addHostConfig(
          int index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder builderForValue) {
        if (hostConfigBuilder_ == null) {
          ensureHostConfigIsMutable();
          hostConfig_.add(index, builderForValue.build());
          onChanged();
        } else {
          hostConfigBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder addAllHostConfig(
          java.lang.Iterable<? extends org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig> values) {
        if (hostConfigBuilder_ == null) {
          ensureHostConfigIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hostConfig_);
          onChanged();
        } else {
          hostConfigBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder clearHostConfig() {
        if (hostConfigBuilder_ == null) {
          hostConfig_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          hostConfigBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public Builder removeHostConfig(int index) {
        if (hostConfigBuilder_ == null) {
          ensureHostConfigIsMutable();
          hostConfig_.remove(index);
          onChanged();
        } else {
          hostConfigBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder getHostConfigBuilder(
          int index) {
        return getHostConfigFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder getHostConfigOrBuilder(
          int index) {
        if (hostConfigBuilder_ == null) {
          return hostConfig_.get(index);  } else {
          return hostConfigBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public java.util.List<? extends org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> 
           getHostConfigOrBuilderList() {
        if (hostConfigBuilder_ != null) {
          return hostConfigBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(hostConfig_);
        }
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder addHostConfigBuilder() {
        return getHostConfigFieldBuilder().addBuilder(
            org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder addHostConfigBuilder(
          int index) {
        return getHostConfigFieldBuilder().addBuilder(
            index, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .org.apache.mesos.logstash.common.LogstashConfig hostConfig = 2;</code>
       */
      public java.util.List<org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder> 
           getHostConfigBuilderList() {
        return getHostConfigFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder> 
          getHostConfigFieldBuilder() {
        if (hostConfigBuilder_ == null) {
          hostConfigBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfig.Builder, org.apache.mesos.logstash.common.LogstashProtos.LogstashConfigOrBuilder>(
                  hostConfig_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          hostConfig_ = null;
        }
        return hostConfigBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.apache.mesos.logstash.common.SchedulerMessage)
    }

    static {
      defaultInstance = new SchedulerMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.apache.mesos.logstash.common.SchedulerMessage)
  }

  public interface ExecutorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.apache.mesos.logstash.common.ExecutorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string frameworkName = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getFrameworkNameList();
    /**
     * <code>repeated string frameworkName = 1;</code>
     */
    int getFrameworkNameCount();
    /**
     * <code>repeated string frameworkName = 1;</code>
     */
    java.lang.String getFrameworkName(int index);
    /**
     * <code>repeated string frameworkName = 1;</code>
     */
    com.google.protobuf.ByteString
        getFrameworkNameBytes(int index);
  }
  /**
   * Protobuf type {@code org.apache.mesos.logstash.common.ExecutorMessage}
   */
  public static final class ExecutorMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.apache.mesos.logstash.common.ExecutorMessage)
      ExecutorMessageOrBuilder {
    // Use ExecutorMessage.newBuilder() to construct.
    private ExecutorMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ExecutorMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ExecutorMessage defaultInstance;
    public static ExecutorMessage getDefaultInstance() {
      return defaultInstance;
    }

    public ExecutorMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ExecutorMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                frameworkName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              frameworkName_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          frameworkName_ = frameworkName_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_ExecutorMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_ExecutorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage.class, org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<ExecutorMessage> PARSER =
        new com.google.protobuf.AbstractParser<ExecutorMessage>() {
      public ExecutorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecutorMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ExecutorMessage> getParserForType() {
      return PARSER;
    }

    public static final int FRAMEWORKNAME_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList frameworkName_;
    /**
     * <code>repeated string frameworkName = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getFrameworkNameList() {
      return frameworkName_;
    }
    /**
     * <code>repeated string frameworkName = 1;</code>
     */
    public int getFrameworkNameCount() {
      return frameworkName_.size();
    }
    /**
     * <code>repeated string frameworkName = 1;</code>
     */
    public java.lang.String getFrameworkName(int index) {
      return frameworkName_.get(index);
    }
    /**
     * <code>repeated string frameworkName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFrameworkNameBytes(int index) {
      return frameworkName_.getByteString(index);
    }

    private void initFields() {
      frameworkName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < frameworkName_.size(); i++) {
        output.writeBytes(1, frameworkName_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < frameworkName_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(frameworkName_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFrameworkNameList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.apache.mesos.logstash.common.ExecutorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.apache.mesos.logstash.common.ExecutorMessage)
        org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_ExecutorMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_ExecutorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage.class, org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage.Builder.class);
      }

      // Construct using org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        frameworkName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.mesos.logstash.common.LogstashProtos.internal_static_org_apache_mesos_logstash_common_ExecutorMessage_descriptor;
      }

      public org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage getDefaultInstanceForType() {
        return org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage.getDefaultInstance();
      }

      public org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage build() {
        org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage buildPartial() {
        org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage result = new org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          frameworkName_ = frameworkName_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.frameworkName_ = frameworkName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage) {
          return mergeFrom((org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage other) {
        if (other == org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage.getDefaultInstance()) return this;
        if (!other.frameworkName_.isEmpty()) {
          if (frameworkName_.isEmpty()) {
            frameworkName_ = other.frameworkName_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFrameworkNameIsMutable();
            frameworkName_.addAll(other.frameworkName_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.apache.mesos.logstash.common.LogstashProtos.ExecutorMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList frameworkName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFrameworkNameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          frameworkName_ = new com.google.protobuf.LazyStringArrayList(frameworkName_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getFrameworkNameList() {
        return frameworkName_.getUnmodifiableView();
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public int getFrameworkNameCount() {
        return frameworkName_.size();
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public java.lang.String getFrameworkName(int index) {
        return frameworkName_.get(index);
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFrameworkNameBytes(int index) {
        return frameworkName_.getByteString(index);
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public Builder setFrameworkName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFrameworkNameIsMutable();
        frameworkName_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public Builder addFrameworkName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFrameworkNameIsMutable();
        frameworkName_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public Builder addAllFrameworkName(
          java.lang.Iterable<java.lang.String> values) {
        ensureFrameworkNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, frameworkName_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public Builder clearFrameworkName() {
        frameworkName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string frameworkName = 1;</code>
       */
      public Builder addFrameworkNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFrameworkNameIsMutable();
        frameworkName_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.apache.mesos.logstash.common.ExecutorMessage)
    }

    static {
      defaultInstance = new ExecutorMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.apache.mesos.logstash.common.ExecutorMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_mesos_logstash_common_LogstashConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_apache_mesos_logstash_common_LogstashConfig_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_mesos_logstash_common_SchedulerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_apache_mesos_logstash_common_SchedulerMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_mesos_logstash_common_ExecutorMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_apache_mesos_logstash_common_ExecutorMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035src/main/proto/logstash.proto\022 org.apa" +
      "che.mesos.logstash.common\"7\n\016LogstashCon" +
      "fig\022\025\n\rframeworkName\030\001 \002(\t\022\016\n\006config\030\002 \002" +
      "(\t\"\240\001\n\020SchedulerMessage\022F\n\014dockerConfig\030" +
      "\001 \003(\01320.org.apache.mesos.logstash.common" +
      ".LogstashConfig\022D\n\nhostConfig\030\002 \003(\01320.or" +
      "g.apache.mesos.logstash.common.LogstashC" +
      "onfig\"(\n\017ExecutorMessage\022\025\n\rframeworkNam" +
      "e\030\001 \003(\tB2\n org.apache.mesos.logstash.com" +
      "monB\016LogstashProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_apache_mesos_logstash_common_LogstashConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_mesos_logstash_common_LogstashConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_apache_mesos_logstash_common_LogstashConfig_descriptor,
        new java.lang.String[] { "FrameworkName", "Config", });
    internal_static_org_apache_mesos_logstash_common_SchedulerMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_apache_mesos_logstash_common_SchedulerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_apache_mesos_logstash_common_SchedulerMessage_descriptor,
        new java.lang.String[] { "DockerConfig", "HostConfig", });
    internal_static_org_apache_mesos_logstash_common_ExecutorMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_apache_mesos_logstash_common_ExecutorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_apache_mesos_logstash_common_ExecutorMessage_descriptor,
        new java.lang.String[] { "FrameworkName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
